### ISSUE TITLE
Missing add-spacer-glyphs.fea

### ISSUE THREAD

**Issue by KazunariTsuboi** [simoncozens/noto-nastaliq-afdko#1]
Makefile and fea files refer to add-spacer-glyphs.fea.
This file seems to be required, but I can't find it in the repository and the build is failing.

**Comment by simoncozens** [comment]
Hello Tsuboi-san! Thanks for getting in touch. I got your message on Twitter but I can't reply to it. Anyway, I have added the missing file to the repository.

**Comment by KazunariTsuboi** [comment]
Thank you very much for your prompt response! I also adjusted the Twitter settings.
